"""
Сервисы для бизнес-логики приложения.
"""
from .auth_service import (
    authenticate_admin,
    create_access_token,
    create_refresh_token,
    verify_token,
    get_admin_by_username,
    get_admin_by_id,
    create_admin,
)
from .user_service import (
    get_user_by_id,
    get_user_by_telegram_id,
    create_user,
    update_user,
    delete_user,
    change_user_status,
    get_users,
    count_users,
    get_user_settings,
    update_user_settings,
)
from .registration_service import (
    create_registration_request,
    get_registration_request_by_id,
    get_registration_requests,
    approve_registration_request,
    reject_registration_request,
    count_registration_requests,
)
from .vpn_session_service import (
    get_vpn_session_by_id,
    get_active_vpn_session_for_user,
    create_vpn_session,
    update_vpn_session_status,
    mark_session_as_connected,
    mark_session_as_confirmed,
    mark_session_reminder_sent,
    disconnect_vpn_session,
    expire_vpn_session,
    get_vpn_sessions,
    get_active_vpn_sessions,
    count_vpn_sessions,
    get_user_vpn_sessions,
    extend_session,
)
from .settings_service import (
    get_setting_by_key,
    get_settings_by_category,
    get_all_settings,
    get_setting_value,
    set_setting,
    delete_setting,
    get_settings_dict,
    get_categories,
)
from .mikrotik_config_service import (
    get_mikrotik_config_by_id,
    get_active_mikrotik_config,
    get_all_mikrotik_configs,
    create_mikrotik_config,
    update_mikrotik_config,
    delete_mikrotik_config,
    test_mikrotik_config_connection,
    get_mikrotik_config_with_decrypted_password,
)
from .mikrotik_service import (
    MikroTikConnectionError,
    get_mikrotik_users,
    create_mikrotik_user,
    delete_mikrotik_user,
    get_firewall_rules,
    enable_firewall_rule,
    disable_firewall_rule,
    find_firewall_rule_by_comment,
    test_mikrotik_connection,
)
from .audit_service import (
    create_audit_log,
    get_audit_logs,
    get_audit_log_by_id,
    count_audit_logs,
    get_user_audit_logs,
    get_admin_audit_logs,
)
from .stats_service import (
    get_overview_stats,
    get_users_stats,
    get_sessions_stats,
    get_registration_requests_stats,
    get_sessions_by_period,
    get_users_by_period,
)
from .database_service import (
    get_database_info,
    create_backup,
    restore_backup,
    verify_database_integrity,
    optimize_database,
    get_backup_list,
)
from .setup_wizard_service import (
    get_setup_wizard_status,
    get_setup_wizard_steps,
    get_setup_wizard_step,
    complete_setup_wizard_step,
    restart_setup_wizard,
    test_telegram_connection,
)

__all__ = [
    # Auth
    "authenticate_admin",
    "create_access_token",
    "create_refresh_token",
    "verify_token",
    "get_admin_by_username",
    "get_admin_by_id",
    "create_admin",
    # User
    "get_user_by_id",
    "get_user_by_telegram_id",
    "create_user",
    "update_user",
    "delete_user",
    "change_user_status",
    "get_users",
    "count_users",
    "get_user_settings",
    "update_user_settings",
    # Registration
    "create_registration_request",
    "get_registration_request_by_id",
    "get_registration_requests",
    "approve_registration_request",
    "reject_registration_request",
    "count_registration_requests",
    # VPN Sessions
    "get_vpn_session_by_id",
    "get_active_vpn_session_for_user",
    "create_vpn_session",
    "update_vpn_session_status",
    "mark_session_as_connected",
    "mark_session_as_confirmed",
    "mark_session_reminder_sent",
    "disconnect_vpn_session",
    "expire_vpn_session",
    "get_vpn_sessions",
    "get_active_vpn_sessions",
    "count_vpn_sessions",
    "get_user_vpn_sessions",
    "extend_session",
    # Settings
    "get_setting_by_key",
    "get_settings_by_category",
    "get_all_settings",
    "get_setting_value",
    "set_setting",
    "delete_setting",
    "get_settings_dict",
    "get_categories",
    # MikroTik Config
    "get_mikrotik_config_by_id",
    "get_active_mikrotik_config",
    "get_all_mikrotik_configs",
    "create_mikrotik_config",
    "update_mikrotik_config",
    "delete_mikrotik_config",
    "test_mikrotik_config_connection",
    "get_mikrotik_config_with_decrypted_password",
    # MikroTik Service
    "MikroTikConnectionError",
    "get_mikrotik_users",
    "create_mikrotik_user",
    "delete_mikrotik_user",
    "get_firewall_rules",
    "enable_firewall_rule",
    "disable_firewall_rule",
    "find_firewall_rule_by_comment",
    "test_mikrotik_connection",
    # Audit
    "create_audit_log",
    "get_audit_logs",
    "get_audit_log_by_id",
    "count_audit_logs",
    "get_user_audit_logs",
    "get_admin_audit_logs",
    # Stats
    "get_overview_stats",
    "get_users_stats",
    "get_sessions_stats",
    "get_registration_requests_stats",
    "get_sessions_by_period",
    "get_users_by_period",
    # Database
    "get_database_info",
    "create_backup",
    "restore_backup",
    "verify_database_integrity",
    "optimize_database",
    "get_backup_list",
    # Setup Wizard
    "get_setup_wizard_status",
    "get_setup_wizard_steps",
    "get_setup_wizard_step",
    "complete_setup_wizard_step",
    "restart_setup_wizard",
    "test_telegram_connection",
]
